version: '3.8'

services:
  ros2_dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        HOSTNAME: ${HOSTNAME}  # 将主机名传递给 Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/workspace